coding-union-kr/youare-iam-be

- build.gradle
- common/src/main/java/com/letter/config/SwaggerConfig.java
- common/src/main/resources/application.yml
#2 
- Gradle 의존성 추가
- SwaggerConfig 추가
- application.yml에 설정 추가
불필요한 설정이 있는지
> feat: Swagger 세팅 #2

- storage/build.gradle
#5 
- Gradle 설정
- storage 모듈에만 QueryDSL 의존성 추가한 것
> feat:QueryDSL 세팅 #5

- storage/build.gradle
- storage/src/main/java/com/letter/member/entity/Couple.java
- storage/src/main/java/com/letter/member/entity/InviteOpponent.java
- storage/src/main/java/com/letter/member/entity/Member.java
- storage/src/main/java/com/letter/question/entity/Answer.java
- storage/src/main/java/com/letter/question/entity/Question.java
- storage/src/main/java/com/letter/question/entity/RegisterQuestion.java
- storage/src/main/java/com/letter/question/entity/SelectQuestion.java
#15 
- ERD를 기반으로 Entity 모두 생성
- Gradle 9.0과 맞지 않는 QueryDSL 의존성 수정
> feat: Entity 생성

- common/build.gradle
- domain/build.gradle
- storage/build.gradle
- storage/src/main/java/com/letter/config/QueryDslConfig.java
- storage/src/main/java/com/letter/member/entity/Couple.java
- storage/src/main/java/com/letter/member/entity/InviteOpponent.java
- storage/src/main/java/com/letter/member/entity/Member.java
- storage/src/main/java/com/letter/question/entity/Answer.java
- storage/src/main/java/com/letter/question/entity/Question.java
- storage/src/main/java/com/letter/question/entity/RegisterQuestion.java
- storage/src/main/java/com/letter/question/entity/SelectQuestion.java
#15 #16 #5 #6 
- Entity `CreatedDate`, `LastModifiedDate` 어노테이션 추가
- QueryDSL Config 파일 추가
- 멀티 모듈 의존성 주입 실패로 패키지 인식 실패 문제 해결
> feat, fix: Entity 변경 사항, Config 파일 추가, Build 실패 해결

- common/src/main/java/com/letter/question/QuestionController.java
- domain/src/main/java/com/letter/question/service/QuestionService.java
- storage/src/main/java/com/letter/question/dto/QuestionResponse.java
- storage/src/main/java/com/letter/question/repository/QuestionCustomRepository.java
- storage/src/main/java/com/letter/question/repository/QuestionCustomRepositoryImpl.java
- storage/src/main/java/com/letter/question/repository/QuestionRepository.java
Close #8 
- 질문 조회 Custom Query 작성
> feat: 질문 조회 #8

- build.gradle
- common/src/main/java/com/letter/CommonApplication.java
- domain/build.gradle
- storage/build.gradle
- CommonApplication 에 `EnableJpaAuditing` 어노테이션 추가
- JPA 의존성을 메인 build.gradle 로 이동
> feat: JPA Auditing 허용

- storage/src/main/java/com/letter/member/entity/Couple.java
- storage/src/main/java/com/letter/member/entity/Member.java
- storage/src/main/java/com/letter/question/entity/Question.java
- Fetch Lazy 추가
- Couple 테이블의 Member FK 삭제
- Member 테이블에 Couple FK 추가
>  refactor: DB 변경으로 인한 코드 변경

- build.gradle
- common/src/main/java/com/letter/member/OAuthController.java
- domain/src/main/java/com/letter/jwt/JwtProperties.java
- domain/src/main/java/com/letter/member/OAuthService.java
- storage/src/main/java/com/letter/member/dto/OAuthResponse.java
#3 
- 카카오에서 가져온 access token 으로 사용자 정보를 가져온다.  
- 가져온 사용자 정보를 이용하여 jwt 토큰 생성한다.
> feat: access token 발급 #3

- storage/src/main/java/com/letter/member/entity/Member.java
- storage/src/main/java/com/letter/question/dto/QuestionResponse.java
- storage/src/main/java/com/letter/question/entity/RegisterQuestion.java
- storage/src/main/java/com/letter/question/repository/QuestionCustomRepositoryImpl.java
- Fetch Lazy 설정 추가
- 필수 생성자 어노테이션으로 대체
- API 명세와 다른 변수명 수정
> refactor: 누락 코드 수정

- storage/src/main/java/com/letter/member/entity/InviteOpponent.java
#31 
- 상대 초대 테이블에 답변 컬럼이 추가되어 해당 엔티티에도 추가함
>  feat: InviteOpponent 엔티티에 칼럼 추가 #31

- common/src/main/java/com/letter/question/QuestionController.java
- domain/src/main/java/com/letter/question/service/QuestionService.java
- storage/src/main/java/com/letter/question/dto/QuestionResponse.java
#26 
- 요구사항에 따른 응답 추가
- Open API 명세 어노테이션 추가
> feat: 질문 선택 API 요구사항 #26

- domain/src/main/java/com/letter/member/OAuthService.java
#34 
- 토큰 생성 시 카카오에서 받아오는 이메일로 설정된 부분을 직접 생성해주는 회원 아이디로 설정 변경
> Feat/auth: jwt 토큰 생성 로직 수정

- common/src/main/java/com/letter/question/AnswerController.java
- domain/src/main/java/com/letter/question/service/AnswerService.java
- storage/src/main/java/com/letter/question/dto/AnswerRequest.java
- storage/src/main/java/com/letter/question/entity/Answer.java
- storage/src/main/java/com/letter/question/repository/AnswerRepository.java
> ex) #이슈번호, #이슈번호
- 요청을 받아 답변 등록
- OpenAPI 명세 설정 추가
> feat: 답변 등록 #11

- common/src/main/java/com/letter/config/WebConfig.java
#40 
- 프론트에서 로그인 api 연동 작업중에 cors 에러가 발생하여 서버에서 해당 에러를 방지하기 위한 config 파일 추가
> Feat/auth: cors 에러 해결을 위한 config파일 추가

- common/src/main/java/com/letter/member/MemberController.java
- domain/src/main/java/com/letter/member/MemberService.java
- storage/src/main/java/com/letter/member/dto/MemberRequest.java
- storage/src/main/java/com/letter/member/dto/MemberResponse.java
- storage/src/main/java/com/letter/member/entity/Couple.java
- storage/src/main/java/com/letter/member/repository/CoupleRepository.java
- storage/src/main/java/com/letter/question/entity/Answer.java
- storage/src/main/java/com/letter/question/entity/SelectQuestion.java
#14 
- 커플 테이블에 정보 등록
- 선택 질문 테이블에 정보 등록
- 답변 테이블에 정보 등록
> Feat/auth: 초대 수락 api #14

- common/src/main/java/com/letter/member/MemberController.java
- domain/src/main/java/com/letter/member/MemberService.java
- storage/src/main/java/com/letter/member/dto/MemberRequest.java
- storage/src/main/java/com/letter/member/dto/MemberResponse.java
#28
- 고유 링크 키로 초대한 회원 이름과 선택 질문 아이디를 response 값으로 내려준다.
> Feat/auth: 초대된 링크로 랜딩되는 페이지 관련 api #28

- common/src/main/java/com/letter/question/QuestionController.java
- domain/src/main/java/com/letter/question/service/QuestionService.java
- storage/src/main/java/com/letter/question/dto/AnswerResponse.java
- storage/src/main/java/com/letter/question/dto/DetailAnswerDto.java
- storage/src/main/java/com/letter/question/dto/LetterDetailResponse.java
- storage/src/main/java/com/letter/question/dto/LetterPaginationDto.java
- storage/src/main/java/com/letter/question/repository/AnswerCustomRepository.java
- storage/src/main/java/com/letter/question/repository/AnswerCustomRepositoryImpl.java
- storage/src/main/java/com/letter/question/repository/QuestionCustomRepositoryImpl.java
#10
- 질문 조회 쿼리 작성
- 답변 조회 쿼리 작성
- 질문 디테일 응답 DTO
- 답변 디테일 응답 DTO
- DB에서 필요한 답변 값을 가져오기 위한 DTO
- 페이징 관련 값을 가진 응답 DTO
- 서비스 로직 구현
- API 작성
- API 명세 설정 추가
> feat: 대화방 질문 리스트 조회 #10

- storage/src/main/java/com/letter/exception/CustomException.java
- storage/src/main/java/com/letter/exception/ErrorCode.java
- storage/src/main/java/com/letter/exception/ExceptionResponse.java
- storage/src/main/java/com/letter/exception/handler/GlobalExceptionHandler.java
#20
- CustomException 생성
- ErrorCode 생성
- ExceptionHandler 생성
- Exception Response 생성
> feat: 커스텀 Exception 생성 #20

- domain/src/main/java/com/letter/question/service/AnswerService.java
- domain/src/main/java/com/letter/question/service/QuestionService.java
- storage/src/main/java/com/letter/exception/ErrorCode.java
#50 
- QuestionService
- AnswerService
> refactor: Question, Answer 예외 핸들링 코드 추가 #50

- .ebextentions
- .github/workflows/deploy.yml
- Dockerrun.aws.json
- common/Dockerfile
- common/build.gradle
- common/src/main/java/com/letter/aws/EbHealthCheck.java
- common/src/main/resources/application-local.yml
- common/src/main/resources/application-prod.yml
- common/src/main/resources/application.yml
- domain/src/main/resources/application-domain.yml
- storage/src/main/resources/application-sotrage.yml
#7 
- deploy.yml 파일 작성
- Parameter store에 환경 변수 등록
- application-prod에 설정 작성
- health check API 작성
- Dockerfile 작성
> deploy: Github Action과 AWS EB를 이용한 배포 #7

- .github/workflows/deploy.yml
- `actions/setup-java@v3`를 사용하는데 `Input required and not supplied: distribution`라는 에러 발생
- `distribution` 추가
> fix: deploy.yml 수정

- common/src/main/java/com/letter/annotation/LoginCheck.java
- common/src/main/java/com/letter/interceptor/LoginCheckInterceptor.java
- common/src/main/java/com/letter/member/MemberController.java
- domain/src/main/java/com/letter/member/MemberService.java
- storage/src/main/java/com/letter/exception/ErrorCode.java
- storage/src/main/java/com/letter/member/dto/MemberResponse.java
- storage/src/main/java/com/letter/member/entity/InviteOpponent.java
- storage/src/main/java/com/letter/member/repository/InviteOpponentCustomRepository.java
- storage/src/main/java/com/letter/member/repository/InviteOpponentCustomRepositoryImpl.java
#60 
- LoginCheck 인터페이스에 `@Inherited` 어노테이션 제거
- 인터셉터 로직 수정
- path 수정(`@PathVariable` 사용)
- 질문 선택 아이디 조회 로직 QueryDsl로 수정 및 타입 변경
> fix:초대 링크로 랜딩되는 페이지 관련 api 수정 및 리팩토링 #60

- .github/workflows/deploy.yml
- common/Dockerfile
- common/src/main/resources/application-prod.yml
- 포트 Spring 기본 포트로 변경
- 환경 이름 변경
> chore: Deploy 관련 파일 수정

- common/src/main/resources/application.yml
- domain/src/main/java/com/letter/question/service/AnswerService.java
- domain/src/main/java/com/letter/question/service/QuestionService.java
- storage/src/main/java/com/letter/member/entity/Couple.java
- storage/src/main/java/com/letter/question/entity/Answer.java
- storage/src/main/java/com/letter/question/repository/AnswerCustomRepositoryImpl.java
- storage/src/main/java/com/letter/question/repository/SelectQuestionRepository.java
#77 
- 답변 테이블 커플 참조키 추가
- 답변 등록 시 couple 참조키를 저장하지 않아 Null로 들어가는 문제 해결
- 답변 등록 시 사용자가 선택된 질문을 등록한 커플에 속하는지 검증하는 부분 추가
- 답변이 조회 시 커플 조건 누락 문제 해결
- 임시 사용자 ID 추상화
> fix: 내 답변이 false로 오는 문제 #77

- .github/workflows/deploy.yml
- build.gradle
- common/build.gradle
- domain/build.gradle
- storage/build.gradle
> chore: 멀티 모듈 설정 수정

- common/src/main/java/com/letter/question/AnswerController.java
- domain/src/main/java/com/letter/question/service/AnswerService.java
- storage/src/main/java/com/letter/question/dto/QuestionContentsResponse.java
- storage/src/main/java/com/letter/question/repository/QuestionCustomRepositoryImpl.java
#81 
- question 응답 DTO 생성
- Question contents만 조회하는 커스텀 쿼리 생성
- 조회 서비스 로직 구현
- OpenAPI 설정 추가
> feat: 답변 등록 렌더링 관련 데이터 조회 #81

- common/build.gradle
- common/src/main/resources/application-prod.yml
> chore: parameter store 관련 설정 변경

- common/src/main/resources/application-prod.yml
> chore: 포트 변호 변경

- domain/src/main/java/com/letter/member/MemberService.java
- storage/src/main/java/com/letter/member/dto/MemberRequest.java
- storage/src/main/java/com/letter/member/dto/MemberResponse.java
#99
- 프론트 요청으로 초대 링크 생성 api에 초대한 사람의 이름을 response에 추가
> feat: 초대 링크 생성 api 에 response 추가 #99

- domain/src/main/resources/application-domain.yml
- storage/src/main/resources/application-sotrage.yml
- parameter store에서 jwt 시크릿 키 받아오지 못하는 문제
> refactor: yml 수정

- domain/src/main/java/com/letter/jwt/JwtProperties.java
> refactor: jwt secret 오타 수정

- common/src/main/java/com/letter/question/AnswerController.java
- common/src/main/java/com/letter/question/QuestionController.java
- common/src/main/resources/application.yml
- domain/src/main/java/com/letter/question/service/AnswerService.java
- domain/src/main/java/com/letter/question/service/QuestionService.java
#106 
- `@LoginCheck` 어노테이션 붙이기
- `@User` 어노테이션으로 사용자 정보 받기
> feat: 질문, 답변 API에 인증, 유저 정보 받기 어노테이션 추가 #106

- common/src/main/resources/application-local.yml
- storage/src/main/java/com/letter/member/entity/Member.java
- storage/src/main/java/com/letter/security/CryptoHelper.java
- storage/src/main/java/com/letter/security/CryptoStringConverter.java
#119
- jpa 컨버터를 사용하여 이메일,이름 암복호화하기
> feat: 사용자 정보 암복호화 #119

- domain/src/main/java/com/letter/question/service/QuestionService.java
- storage/src/main/java/com/letter/question/dto/LetterPaginationDto.java
#121 
- ResponseDTO에 myID 추가
- setter로 값 담기
> refactor: 대화 상세 API 요구사항 추가 #121

- common/src/main/java/com/letter/member/OAuthController.java
- domain/src/main/java/com/letter/jwt/JwtProvider.java
- domain/src/main/java/com/letter/member/OAuthService.java
- storage/src/main/java/com/letter/exception/ErrorCode.java
- storage/src/main/java/com/letter/member/entity/Member.java
- storage/src/main/java/com/letter/member/repository/MemberCustomRepositoryImpl.java
#12 
- ErrorCode enum에 code 추가
- JwtProvider에 Refresh token 발급 메서드 추가
- 로그인 관련 메서드에 Refresh token 발급하고 DB에 저장하는 로직 추가
- DB에 저장한 Refresh token으로 새로운 Access token 발급 하는 API 생성
> feat: Refresh token 발급 #12

- storage/src/main/java/com/letter/exception/ErrorCode.java
- ErrorCode 구조 변경
- code 중복 해결
> refactor: ErrorCode에서 code 중복 수정

- common/src/main/resources/application-local.yml
- common/src/main/resources/application-prod.yml
- common/src/main/resources/application.yml
#132
- prod, local 나눴던 yml 설정 파일 합치기
- DB Query 로그는 local 환경에서만 나오게 수정
> chore: Beanstalk 환경 변수 세팅 #132

- common/src/main/java/com/letter/interceptor/LoginCheckInterceptor.java
- common/src/main/java/com/letter/interceptor/LoginUserArgumentResolver.java
- domain/src/main/java/com/letter/exception/ErrorCode.java
- domain/src/main/java/com/letter/jwt/JwtProvider.java
- domain/src/main/java/com/letter/member/OAuthService.java
#131 
- ErrorCode에서 401 에러 정리
- Refresh token 관련 에러코드 추가
> refactor: Refresh token 요구사항에 따라 변경 #131

- domain/src/main/java/com/letter/jwt/JwtProvider.java
- domain/src/main/java/com/letter/member/OAuthService.java
> feat: 만료된 토큰 검증 추가 #138

- common/src/main/java/com/letter/question/QuestionController.java
- storage/src/main/java/com/letter/question/repository/QuestionCustomRepositoryImpl.java
#143 
- `nextCursor Default "0"`으로 변경
- 쿼리 조건도 `nextCursor == 0`으로 변경
> fix: nextCursor 1일 때 생기는 문제 해결 #143

- common/src/main/java/com/letter/member/OAuthController.java
- domain/src/main/java/com/letter/jwt/JwtProvider.java
- domain/src/main/java/com/letter/member/OAuthService.java
- storage/src/main/java/com/letter/member/entity/Member.java
#137 
- 요청 헤더로 받은 만료된 토큰 검증 & 사용자 확인
- DB에 저장된 Refresh token `null`로 변경
- 205로 응답
> feat: 로그아웃 API 추가 #137

- storage/src/main/java/com/letter/member/dto/MemberStatusResponse.java
- storage/src/main/java/com/letter/member/dto/role/UserStatusRole.java
- MemberStatusResponse
- UserStatusRole
> fix: 사용자 상태 검사 누락 파일 추가

- domain/src/main/java/com/letter/member/MemberService.java
#149 
- 초대 수락 api 에 초대한 사람과 초대된 사람과 같은지 체크하여 같을 경우 에러를 던지는 부분 수정
> fix: 초대 수락 api 에 초대한 사람과 초대된 사람이 같은지 체크하는 부분 수정 #149

- common/src/main/java/com/letter/config/SwaggerConfig.java
- common/src/main/java/com/letter/interceptor/LoginUserArgumentResolver.java
- common/src/main/java/com/letter/member/MemberController.java
- domain/src/main/java/com/letter/exception/ErrorCode.java
- domain/src/main/java/com/letter/member/MemberService.java
- storage/src/main/java/com/letter/member/dto/MemberRequest.java
- storage/src/main/java/com/letter/member/dto/MemberResponse.java
- storage/src/main/java/com/letter/member/dto/MemberStatusResponse.java
- storage/src/main/java/com/letter/member/entity/Member.java
- storage/src/main/java/com/letter/security/CryptoHelper.java
#30 
- Member 도메인 코드 리뷰
- 에러 코드 응답 설정 추가
- Response, Request DTO 설명 추가
- 인증 관련 설정 추가
> feat, refactor: Member 도메인 Swagger 설정 추가 및 변경 #30

- storage/src/main/java/com/letter/member/entity/InviteOpponent.java
- storage/src/main/java/com/letter/question/entity/Answer.java
#52 
- Answer 테이블 `answerContents` 암호화 컨버팅
- InviteOpponent 테이블 `answer` 암호화 컨버팅
> feat: 사용자 답변 암호화 #52

- common/src/main/java/com/letter/interceptor/LoginUserArgumentResolver.java
- storage/src/main/java/com/letter/security/CryptoHelper.java
> comment: 불필요한 정보성 로그 삭제 #153

- domain/src/main/java/com/letter/exception/ErrorCode.java
- domain/src/main/java/com/letter/question/service/QuestionService.java
- storage/src/main/java/com/letter/question/repository/SelectQuestionCustomRepository.java
- storage/src/main/java/com/letter/question/repository/SelectQuestionCustomRepositoryImpl.java
#53
- SelectQuestionCustomRepository 생성
- 1일 1질문 검증 로직 추가
> feat: 하루에 질문 한개 등록 제한 기능 추가 #53

- .ebextensions
- .ebextensions/00-set-timezone.config
- common/src/main/java/com/letter/CommonApplication.java
- domain/src/main/java/com/letter/question/service/QuestionService.java
- domain/src/main/java/com/letter/scheduler/LockedQuestionsScheduler.java
- storage/src/main/java/com/letter/question/dto/LockedSelectQuestionDto.java
- storage/src/main/java/com/letter/question/entity/SelectQuestion.java
- storage/src/main/java/com/letter/question/repository/AnswerCustomRepositoryImpl.java
- storage/src/main/java/com/letter/question/repository/QuestionCustomRepositoryImpl.java
- storage/src/main/java/com/letter/question/repository/SelectQuestionCustomRepositoryImpl.java
#166 
- 7일이 지난 답변이 2개 미만인 선택 질문 조회 쿼리 작성
- 해당 질문 노출 여부 N으로 변경
- 배포 서버 한국 시간으로 변경
> feat: 7일 지난 잠긴 질문 비공개 처리 #166

- common/src/main/java/com/letter/CommonApplication.java
> feat: 컨테이너 내의 서버 시간 설정 추가

- common/src/main/java/com/letter/question/AnswerController.java
- domain/src/main/java/com/letter/question/service/AnswerService.java
- storage/src/main/java/com/letter/question/dto/ModifyAnswerRequest.java
- storage/src/main/java/com/letter/question/entity/Answer.java
- storage/src/main/java/com/letter/question/repository/AnswerRepository.java
- storage/src/main/java/com/letter/question/repository/SelectQuestionCustomRepositoryImpl.java
#173 
- 스웨거 설정 추가
- 조회 커스텀 쿼리 작성
> feat: 답변 수정 #173

- common/src/main/java/com/letter/question/AnswerController.java
- domain/src/main/java/com/letter/exception/ErrorCode.java
- domain/src/main/java/com/letter/question/service/AnswerService.java
- storage/src/main/java/com/letter/question/dto/AnswerContentsResponse.java
- storage/src/main/java/com/letter/question/repository/AnswerCustomRepositoryImpl.java
- storage/src/main/java/com/letter/question/repository/SelectQuestionCustomRepositoryImpl.java
#175 
- 겹치는 path 수정
- 커스텀 쿼리 작성
> feat: 기존 답변 조회 #175

- storage/src/main/java/com/letter/member/entity/Member.java
- 유효성 검사 의존성 추가로 유효성 어노테이션이 제대로 작동해서 발생했음
- Refresh token이 길어서 컬럼 제약 조건을 수정했었는데 코드에서는 수정하지 않아서 발생한 문제
> fix: 로그인이 되지 않는 이슈 해결

- storage/src/main/java/com/letter/member/entity/InviteOpponent.java
- storage/src/main/java/com/letter/question/entity/Answer.java
- 1000자 문자열을 암호화하면 4000자 이상으로 늘어남
- 때문에 SQL Exception 발생하는 문제 확인
- 테이블 컬럼의 제약조건 수정으로 해결
> fix: 답변 저장 이슈 해결

- common/src/main/java/com/letter/question/AnswerController.java
- domain/src/main/java/com/letter/question/service/AnswerService.java
> refactor: 제네릭 와일드 카드 수정

- common/src/main/java/com/letter/member/MemberController.java
#197 
- 초대 링크 생성 응답 상태코드 수정
- 초대 링크 수락 응답 상태코드 수정
> refactor: 상태코드가 API 명세와 다른 부분 수정 #197

- common/src/main/java/com/letter/member/OAuthController.java
- common/src/main/java/com/letter/question/AnswerController.java
- common/src/main/java/com/letter/question/QuestionController.java
- domain/src/main/java/com/letter/member/OAuthService.java
- domain/src/main/java/com/letter/question/service/AnswerService.java
- domain/src/main/java/com/letter/question/service/QuestionService.java
- storage/src/main/java/com/letter/question/dto/LetterPaginationResponse.java
#192 
- Service에서 ResponseEntity 분리! 오직 Controller에서만
> refactor: ResponseEntity 서비스단과 분리 #192

- domain/src/main/java/com/letter/member/MemberService.java
- domain/src/main/java/com/letter/question/service/QuestionService.java
- storage/src/main/java/com/letter/member/repository/CoupleCustomRepositoryImpl.java
- storage/src/main/java/com/letter/member/repository/CoupleRepository.java
- storage/src/main/java/com/letter/member/repository/InviteOpponentCustomRepositoryImpl.java
- storage/src/main/java/com/letter/member/repository/InviteOpponentRepository.java
- storage/src/main/java/com/letter/question/repository/QuestionCustomRepositoryImpl.java
- storage/src/main/java/com/letter/question/repository/QuestionRepository.java
- storage/src/test/java/com/letter/member/repository/InviteOpponentRepositoryTest.java
#195 
- 추후 노출여부 관련 기능이 추가되어 잘못된 데이터가 불어와지는 것을 우려해서 고치기로 결정
> fix: isShow로 조회하지 않는 쿼리 전부 수정 #195

- domain/src/main/java/com/letter/member/MemberService.java
#205
- Long 타입의 countOpenSelectQuestion 변수 null 체크
> fix: 커플이 모두 답변을 등록한 질문 카운트 부분에서 NullPointerException 발생 #205
